name: Update Feature Branches with Workflow Changes

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'

jobs:
  update-feature-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: List feature branches
        id: list_branches
        run: |
          branches=$(git branch -r | grep 'origin/feature/' | sed 's/origin\///')
          echo $branches
          echo "BRANCHES=$(echo $branches | tr ' ' ',')" >> $GITHUB_ENV

      - name: Update feature branches
        run: |
            # Convert comma-separated list to newline-separated list
            branches=$(echo "${{ env.BRANCHES }}" | tr ',' '\n')

            # Loop through each branch and process it
            while IFS= read -r branch; do
                # Check if the branch starts with 'feature/'
                if [[ "$branch" == feature/* ]]; then
                echo "Processing branch: $branch"
                git checkout "$branch"
                git merge origin/dev --no-ff --no-edit || {
                    echo "Merge failed for branch $branch. Details:"
                    git status
                    git diff
                    exit 1
                }
                git push origin "$branch"
                else
                echo "Skipping branch: $branch (does not start with 'feature/')"
                fi
            done <<< "$branches"

      - name: Clean up
        run: |
          git checkout dev
