version: "3.4"

services:
  app:
    image: flaskdockerstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - 5000:5000
    volumes:
      - .:/flask_starterkit:cached
    env_file: .env
  unit-test-container:
    image: unit-test-container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_test
    env_file: .env
