services:

  nginx:
    
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - node-app
  
  node-app:
  
    build: 
      context: ../DevOps-with-Docker-and-Node/
      target: development
    volumes:
      - ../DevOps-with-Docker-and-Node/:/app
      - /app/node_modules
    deploy:
      replicas: 2
    environment:
      PORT: ${PORT}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET} 
      JWT_EXPIRY: ${JWT_EXPIRY}
      COOKIE_NAME: ${COOKIE_NAME}
      CLIENT_PORT: ${CLIENT_PORT}
      EMAIL: ${EMAIL}
      KEY: ${KEY}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT} 

    command: ["npm", "run", "dev"]
    depends_on:
      - database
  
  database:
    image: mysql:5.7   
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: